### ISSUE TITLE
[Bug] Crash on Game Quit (Rare)

### ISSUE THREAD

**Issue by Master-64** [shiversoftdev/t7patch#10]
Just like it says in the title. Only had this happen once in about 20 tries. Not a big deal, but worth reporting.

**Comment by shiversoftdev** [comment]
If you send your crashes.log I can see about looking into this

**Comment by framilano** [comment]
Yep, happens to me as well.
But not when I manually type quit in console.

**Comment by shiversoftdev** [comment]
no crash log submitted, closing.
