### ISSUE TITLE
Game Blackscreens on open; Start the patch slightly after the intro screen finishes.

### ISSUE THREAD

**Issue by TheSp1piT** [shiversoftdev/t7patch#18]
Started up the 1.06 patch, told me it has a newer version i went to donwload it, started and everytime i start a match, whether it's zombie or campaign either it freezes on the intro animation or when it's loading the map or mission

**Comment by shiversoftdev** [comment]
check your BO3 root directory for crashes.log and send it here.

**Comment by SWANMUSTDIE** [comment]
I have a simillar issue where my game will become a black screen after a certain amount of time. Happened with 1.06 and 1.07
[crashes.log](https://github.com/shiversoftdev/t7patch/files/10329943/crashes.log)

**Comment by shiversoftdev** [comment]
Does not seem to be relevant to the patch. Crashing at some irrelevant function that the patch does not touch at all. I recommend reinstalling your game.

**Comment by shiversoftdev** [comment]
(reopened because I didnt notice crash log was not from OP

**Comment by RGB00255** [comment]
Same for me, when I run t7patch before Black Ops 3 it will crash the game but if I run the patch after loading to the main menu it works fine. 
[errors.txt](https://github.com/shiversoftdev/t7patch/files/10331839/errors.txt)

**Comment by RGB00255** [comment]
> Same for me, when I run t7patch before Black Ops 3 it will crash the game but if I run the patch after loading to the main menu it works fine. [errors.txt](https://github.com/shiversoftdev/t7patch/files/10331839/errors.txt)

Actually disregard this, could have been something on my end as it works if I run t7patch before I run the game. Thanks for the effort by the way, it is appreciated!
