### ISSUE TITLE
Feature Request: On update prevent injection unless an ignore button is pressed.

### ISSUE THREAD

**Issue by ZimbaMontagne** [shiversoftdev/t7patch#19]
Since there is no auto update for the patch it would be nice if instead of injecting on an update notice that it gave an option instead.

1. To ignore the patch and inject anyways. 
2. Do not inject the patch and optionally open a link to the [github patch page](https://github.com/shiversoftdev/t7patch/releases/tag/Current).  

Preventing the injection makes it easier for me to delete the older patch as I habitually open up bo3 before the patch.

**Comment by shiversoftdev** [comment]
May set this up as a config option as it is technically not a good idea to have bo3 open without the patch injected, so it would be at your own risk.

**Comment by ZimbaMontagne** [comment]
Why is it worse to open the game first? Doesn't seem to make a difference as long as the injection goes into effect before launching into multiplayer.  Is there a particular reason to launch the patch first?

**Comment by shiversoftdev** [comment]
The game starts the network connection during the load screen. You have no control over when you connect to online services.

**Comment by ZimbaMontagne** [comment]
Ah good to know thanks,  Ill add an another suggestion at least for first time setup or turn off in the config a warning about that.
