### ISSUE TITLE
could you fix the subtitle lag, the game is very stuck in the paticular language

### ISSUE THREAD

**Issue by esp-ra-de-alice-clones** [shiversoftdev/t7patch#21]
Tradition and simple chinese subtitles will cause the game lag and stutter everytime the sub appears, no update and fix for this old game bug issue is real a shamed move for activition, is there any chance to patch game to fix the tc sc subtutles problem? thanks so much

**Comment by shiversoftdev** [comment]
I'd love to help, but unfortunately, I really don't even know where to begin with this, and it is far outside of the scope of the community patch.
