### ISSUE TITLE
Not able to find or Host Public Games while running the Tool

### ISSUE THREAD

**Issue by crustySenpai** [shiversoftdev/t7patch#26]
Did i read the FAQ: Yes
Did i watch the Tutorial: Yes
Which Version of the Patch: 2.00
Which Gamemode i'm trying: Zombies

Like the Title says i'm not able to find or Host Public Games when running the Tool, i don't have a Network Password set and also tried with and without the option Friends Only.
I also tried to go without Name Spoofing which also didn't help. There is no Error or Crash log i could provide since it didn't generate one.
Tried with and without the provided LPC Folder aswell.
I also tried to just wait when it checks if any Lobbies are available to host an own but then it just kicks me back to the Zombies Menu.
Without the Tool i could go Online and find / host Lobbies just fine.

If i overlooked something then i'm sorry and just skip over the issue.
![Screenshot_3](https://user-images.githubusercontent.com/83429736/225522256-0ae69d93-daaa-4ea9-94d0-b337c89c7360.png)

**Comment by shiversoftdev** [comment]
I'll look into this later, but it is kind of a non-issue considering the patch is not really meant for public lobbies.

**Comment by crustySenpai** [comment]
no worries just figured it's maybe worth mentioning

**Comment by iClixz** [comment]
I completely understand that the patch mainly focuses on making the game better and safer for solo/private play, but it also massively improves the performance of the game all around.  It would be greatly appreciated to have this issue fixed so that the people who do enjoy public matches in zombies/multiplayer can do so with good performance.

**Comment by FalconeXX1** [comment]
sam for me , i hope will be fixed

**Comment by BotanKun11** [comment]
Same i wanta play steam steam matchmaking MP again

**Comment by maskfirer** [comment]
I found that when I first enter the match in the lobby and then open t7patch it works fine, but the battle end I can't continue to the next game

**Comment by VoviTekk** [comment]
> I found that when I first enter the match in the lobby and then open t7patch it works fine, but the battle end I can't continue to the next game

True that happening to me all the time ._.

**Comment by SushyDev** [comment]
vouch for separate fps fix patch

**Comment by shiversoftdev** [comment]
> vouch for separate fps fix patch

not happening.

**Comment by weichii** [comment]
yeah playing online and hosting games would be so awesome :) can only agree with everyone

**Comment by xiltyx** [comment]
ye pls fix this, would be awesome
