### ISSUE TITLE
[Bug/Request] Changing 'playername' in settings to more than 15 characters causes a crash

### ISSUE THREAD

**Issue by NeverEndingCycle** [shiversoftdev/t7patch#30]
I was unaware the GUI had a char limit and I accidentally bypassed it when messing with the settings file.

The bug is that the error it causes is non-descriptive and changing a name string probably shouldn't result in a full crash.

 The request is that you allow for names longer than 15 characters like normal steam names (mine is 16).

**Comment by shiversoftdev** [comment]
This may be a bug in that the tool should be checking name length when loading the config, but the limit is 15 for a reason. Your request is denied, and I will add the length check.
