### ISSUE TITLE
Adobe Lightroom making the game crash's/freeze's

### ISSUE THREAD

**Issue by ZynAryane** [shiversoftdev/t7patch#42]
Lightroom is making the game crash's/freeze's when the patch is open in same time as Lightroom

I know closing Lightroom is the solution, its just a QOL that can be fixed!

Tried multiple time's with or w/o Lightroom and always the same result,

When Lightroom is open, the patch crash's/freeze's my game
When LR is not open no crash's/freeze's occur

**Comment by shiversoftdev** [comment]
Then dont use lightroom!
