### ISSUE TITLE
Steam wrapper

### ISSUE THREAD

**Issue by ShayBox** [shiversoftdev/t7patch#45]
This could be made into a wrapper to auto-launch with the game using Steam launch options, you would just have to extend the functionality to take the game binary location as an argument and launch the game from your own process

**Comment by shiversoftdev** [comment]
No.

**Comment by ShayBox** [comment]
Then open source the program/patch source code so it can be forked, both so the source can be observed and trusted, and so that functionality can be patched into the patch 🤔
