### ISSUE TITLE
Errors sometimes upon launch

### ISSUE THREAD

**Issue by BoxOfMysteriez** [shiversoftdev/t7patch#46]
Sometimes while running the patch, the UI will be displayed in red and say an error has occurred a bit before the game completely opens. However, once the game full opens the UI will change to orange and say the process is protected. I have attached my errors.txt file that was generated. Just wanted to know if this was a known issue, and/or if it indicated something isn't working properly.  
[errors.txt](https://github.com/shiversoftdev/t7patch/files/11659699/errors.txt)

**Comment by shiversoftdev** [comment]
If it ends up saying game is protected, its fine.
