### ISSUE TITLE
Usermaps not working co-op?

### ISSUE THREAD

**Issue by BoxOfMysteriez** [shiversoftdev/t7patch#53]
As of today, I haven't been able to load into any custom maps with usermaps loaded co-op. Game will always hang on the loading screen during "synchronizing" or "waiting for other players". Vanilla maps seem to work fine however. Unsure if the recent Steam updates broke aspects of the patch, or the vanilla game is broken. I have provided my errors file if that helps. 
[errors.txt](https://github.com/shiversoftdev/t7patch/files/11805653/errors.txt)

**Comment by shiversoftdev** [comment]
Not an issue, we play customs all the time.
