### ISSUE TITLE
Immediate crash under Wine

### ISSUE THREAD

**Issue by tpurde** [shiversoftdev/t7patch#6]
Hey there. I know Linux is not the target audience for this patch, but with the release of the Deck, there are a couple of players trying to enjoy Black Ops III on Linux. Is it in any way possible to make this patch work with Wine? If you don't have Linux, I'm willing to send you logs, do testing or do anything you might need to get it working, should you wish so.

**Comment by shiversoftdev** [comment]
At this time the target for this patch is Windows only. There are lots of Windows-only tricks used internally that probably aren't working on whine which is why you crash.
