### ISSUE TITLE
[Bug] Injection Freeze (Rare)

### ISSUE THREAD

**Issue by Master-64** [shiversoftdev/t7patch#9]
Seems to be quite random and inconsistent, but at times, upon the code being injected into BO3, the game will outright freeze. When this occurred for me (only once so far), I had just closed the game without closing the tool, then booted up BO3 again (after roughly 5 or so minutes). I haven't been able to replicate this since then.

**Comment by shiversoftdev** [comment]
Freeze on inject is known and its due to the RPC I use in the external tool. It only ever happens when arxan is running checks at the same time I inject. At this time its a will-not-fix because it doesn't technically affect the game at all.
